### ISSUE TITLE
Создание аэропорта с пустым названием

### ISSUE THREAD

**Issue by Rsengo** [swash66/swashrsengo#1]
При открытии формы программа просит ввести название аэропорта. Если оставить это поле пустым и нажать "Создать аэропорт", программа продолжит работать, создав аэропорт без названия. 

![b-4kndkfj0c](https://cloud.githubusercontent.com/assets/26200531/26287293/d4c2e874-3ea2-11e7-9ea0-613c2b94300f.jpg)

**Comment by swash66** [comment]
Была исправлена данная ошибка путем проверки перед выполнением botton1.mouseclick() заполненности textbox1. Если текстбокс пустой, то программа не даст пользователю создать аэропорт до тех пор, пока он не задаст название аэропорту.

**Comment by Rsengo** [comment]
Ошибка, действительно, была устранена.
