### ISSUE TITLE
Нет валидации поля "Грузоподъемность" при создании самолета

### ISSUE THREAD

**Issue by Rsengo** [swash66/swashrsengo#2]
В поле "Грузоподъемность" при создании самолета можно указать не числовое значение (текст). Если заполнить это поле строковыми символами, то компилятор не может заполнить этими свойствами поле типа int и программа перестает работать.

![wqwrcged3yg](https://cloud.githubusercontent.com/assets/26200531/26287292/c79707b6-3ea2-11e7-9a3a-39121d5d0462.jpg)

**Comment by swash66** [comment]
Была исправлена данная ошибка путем проверки содержимого  textbox5. Если текстбокс содержит значение не типа int, то программа не позволит создать самолет, пока пользователь не введет в данный текстбокс значение типа int.

**Comment by Rsengo** [comment]
Ошибка, действительно, была исправлена.
